language: python
python:
    - "2.6"
    - "2.7"
install:
   - cd static_html_generation
   - pip install -r requirements --use-mirrors
   - cd ../front_end
   - npm install -g grunt-cli grunt-init
   - npm install
   - sudo apt-get install phantomjs
script:
    - export PYTHONPATH=.
    - cd static_html_generation
    - nosetests
    - cd ../front_end
    - grunt jasmine
