language: python
python:
    - "2.6"
    - "2.7"
install:
   - cd static_html_generation
   - pip install -r requirements.txt --use-mirrors
   - cd ..
   - echo "yes" | sudo add-apt-repository ppa:chris-lea/node.js
   - sudo apt-get update
   - sudo apt-get install nodejs phantomjs
   - sudo npm install -g grunt-cli grunt-init
   - npm install
script:
    - export PYTHONPATH=.
    - cd static_html_generation
    - nosetests
    - cd ..
    - grunt jasmine
