language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/node_modules
matrix:
  include:
    - python: '2.7'
    - python: '3.3'
    - python: '3.4'
    - python: '3.5'
    - python: '3.5'
      addons:
        sauce_connect: true
      env:
        - secure: "iexai8u5b/bIEXUKrKwjitHExazyoYqRiKvXefexIKnfdETCDRQ5bBnahpqzJD8x1gnJ3kgPptcEW1kBR2mSOcwPm77kjivGzW404EN+1gZb7eFn88lKuIstjw4zcpOPIpVMxhfVe1K+nVWKkJJf1tpJsW9KaZsdiJMyoHKdq4s="
        - secure: "eBEPhov8FBlBOFyRskkqtbv0+74nUuq9ou6aSRHJyNoPRCsvMv3akTNSwygmg5vqe4Qp7pKKZjaVoXX6KFtC3/2Auc08t7VbyTBQHbEnaJjkFBaZSJKOpNUcWBnTHvRwPhkjzc9N1DaHwKCrf50aItT98TL6QRGKMrfbxyxuJ/g="
before_install:
  - pip install -U pip wheel
  - rm -rf ~/.nvm
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 4.4.0
  - nvm use 4.4.0
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - npm install -g grunt-cli
  - ./frontendbuild.sh
script:
  - if [ -z "$SAUCE_ACCESS_KEY" ]; then ./unit-tests.sh; fi
  - if [ ! -z "$SAUCE_ACCESS_KEY" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./integration-tests.sh; fi
