language: python
python:
    - "2.6"
    - "2.7"
install:
   - cd regserver 
   - pip install -r requirements.txt --use-mirrors
   - pip install -r requirements-test.txt --use-mirrors
   - cd ..
   - echo "yes" | sudo add-apt-repository ppa:chris-lea/node.js
   - sed -i "s/\"grunt-casperjs\":.*/\"grunt-casperjs\":\"git:\/\/github.com\/theresaanna\/grunt-casperjs.git\",/g" package.json
   - sudo apt-get update
   - sudo apt-get install nodejs phantomjs
   - sudo npm install -g grunt-cli grunt-init
   - sudo npm install -g casper
   - sudo npm install
   - cp example-config.json config.json
   # We will also run the api locally
   - git clone https://github.com/eregs/regulations-core.git
   - pip install zc.buildout
   - buildout
script:
    - cd regserver
    - python manage.py test regulations --settings=regserver.settings.dev
    - cd ..
    - cd regulations-core
    - ./bin/django syncdb
    - ./bin/django migrate
    - ./bin/django runserver 8282 &
    - sleep 5 # give django enough time to startup
    - curl http://localhost:8282/notice
    - cd ..
    - grunt test
