language: python
python:
    - "2.6"
    - "2.7"
install:
   - cd regserver 
   - pip install -r requirements.txt --use-mirrors
   - pip install -r requirements-test.txt --use-mirrors
   - cd ..
   - echo "yes" | sudo add-apt-repository ppa:chris-lea/node.js
   - sudo apt-get update
   - sudo apt-get install nodejs phantomjs
   - git clone git://github.com/n1k0/casperjs.git
   - cd casperjs
   - sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs
   - casperjs
   - npm install grunt-cli grunt-init
   - npm install
   - cp example-config.json config.json
script:
    - cd regserver
    - python manage.py test regulations --settings=regserver.settings.dev
    - cd ..
    - grunt test
