language: python
python:
    - "2.6"
    - "2.7"
install:
   - cd regserver 
   - pip install -r requirements.txt --use-mirrors
   - pip install -r requirements-test.txt --use-mirrors
   - cd ..
   - echo "yes" | sudo add-apt-repository ppa:chris-lea/node.js
   - sudo apt-get update
   - sudo apt-get install nodejs phantomjs
   - npm -v
   - npm install grunt-cli grunt-init casper
   - npm install
   - sudo npm install -g
   - cp example-config.json config.json
script:
    - cd regserver
    - python manage.py test regulations --settings=regserver.settings.dev
    - cd ..
    - grunt test
