language: python
python:
    - "2.6"
    - "2.7"
install:
   - cd regserver 
   - pip install -r requirements.txt --use-mirrors
   - pip install -r requirements-test.txt --use-mirrors
   - cd ..
   - echo "yes" | sudo add-apt-repository ppa:chris-lea/node.js
   - sed -i !"s/\"grunt-casperjs\": .*/\"grunt-casperjs\": \"git:\/\/github.com\/theresaanna\/grunt-casperjs.git\",/g" package.json
   - sudo apt-get update
   - sudo apt-get install nodejs phantomjs
   - npm install grunt-cli grunt-init
   - sudo npm install -g casper
   - npm install
   - cp example-config.json config.json
script:
    - cd regserver
    - python manage.py test regulations --settings=regserver.settings.dev
    - cd ..
    - grunt test
